include:
  - services/3xui/compose.yml
  - services/mtproxy/compose.yml

services:
  # PROXY
  traefik:
    image: traefik:v3.4
    restart: always
    container_name: traefik
    user: "0:0"  # Run as root to access the acme.json file
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme/acme.json:/acme/acme.json
