# Entry Points
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

# Provider for Docker
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

# Certificate Resolvers
[certificatesResolvers.letsencrypt.acme]
  email = "tls@hudalla.dev"
  storage = "/acme/acme.json"
  # Use staging for testing to avoid rate limits
  # caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  keyType = "EC256"
  # Only renew certificates 30 days before expiry
  [certificatesResolvers.letsencrypt.acme.httpChallenge]

# Global configuration to reduce checks
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

# API and Dashboard (optional - remove if not needed)
[api]
  dashboard = false
  insecure = false
