volumes:
  nextcloud_aio_mastercontainer: # This volume stores the AIO master container's configuration

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.chhoto-url.rule=Host(`nc.eu1.hudalla.dev`)
      - traefik.http.routers.chhoto-url.entrypoints=websecure
      - traefik.http.routers.chhoto-url.tls.certresolver=letsencrypt
      - traefik.http.services.chhoto-url.loadbalancer.server.port=8443
      # HTTP to HTTPS redirect
      - traefik.http.routers.chhoto-url-http.rule=Host(`nc.eu1.hudalla.dev`)
      - traefik.http.routers.chhoto-url-http.entrypoints=web
      - traefik.http.routers.chhoto-url-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # Required for AIO configuration and backups
      - /var/run/docker.sock:/var/run/docker.sock:ro # Required for AIO to manage other Docker containers
      - ./data:/mnt/ncdata # This is your Nextcloud user data directory on the host
    environment:
      # Optional: Set your desired Nextcloud data directory on the host
      - NEXTCLOUD_DATADIR=/mnt/ncdata
