services:
  chhoto-url:
    image: sintan1729/chhoto-url:latest
    restart: unless-stopped
    container_name: chhoto-url
    labels:
      - traefik.enable=true
      - traefik.http.routers.chhoto-url.rule=Host(`l.eu1.hudalla.dev`)
      - traefik.http.routers.chhoto-url.entrypoints=websecure
      - traefik.http.routers.chhoto-url.tls.certresolver=letsencrypt
      - traefik.http.services.chhoto-url.loadbalancer.server.port=4567
      # HTTP to HTTPS redirect
      - traefik.http.routers.chhoto-url-http.rule=Host(`l.eu1.hudalla.dev`)
      - traefik.http.routers.chhoto-url-http.entrypoints=web
      - traefik.http.routers.chhoto-url-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    environment:
      - db_url=/db/urls.sqlite
      - password=${CHHOTO_URL_PASSWORD}
    volumes:
      - ./data/:/db
